## Overview

In the world of data science, mastering pandas is like learning to reading before writing poetry

### origin story

It was made to solve a problem. In 2008 Wes Mckinney started making pandas that time wes worked at a fin tech company and he needed a library to manage and analyze large databases thats why he started making pandas

### use cases

- Data cleaning
- Data analysis
- Data trinsformation
- Data visualization (basic level)
- Data aggregation
- File handling
- Data filtering and selection
- Time series analysis

### Index

- Series
- Dataframes
- Missing data
- Merging, joining concatenation
- GroupBy and Aggregations
- Pivot Tables and crosstab
- Operations
- Working with real data
- Some great capstone project

### 1. Series

A series is a one-dimensional labeled array capable of holding any data type. The axis labels are collectively called the index

### Creating series

There are multiple ways to create a pandas series

In [70]:
import numpy as np
import pandas as pd

In [71]:
labels = ['a', 'b', 'c']
my_list = [10, 20, 30]
my_arr = np.array([10, 20, 30])
d = {1:10, 2:20, 3:30}

In [72]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [73]:
pd.Series(my_list, index=labels)

a    10
b    20
c    30
dtype: int64

In [74]:
pd.Series(my_arr)

0    10
1    20
2    30
dtype: int64

In [75]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

### 2. Data Frames

#### creating a dataframe

In [76]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]   
]

lsit_df = pd.DataFrame(data_list)
columns = ['Name', 'Age', 'City', 'Salary']
list_df = pd.DataFrame(data_list, columns=columns)

In [77]:
print(list_df)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [78]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [20, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data=data)

In [79]:
print(df)

    Name  Age      City  Salary
0   John   20  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### Selection and indexing of columns

In [80]:
df

    Name  Age      City  Salary
0   John   20  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [81]:
df['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [82]:
df[['Age', 'City']]

   Age      City
0   20  New York
1   34     Paris
2   29    Berlin
3   42    London

In [83]:
df[['Age', 'City', 'Salary']]

   Age      City  Salary
0   20  New York   65000
1   34     Paris   70000
2   29    Berlin   62000
3   42    London   85000

#### Creating a new column

In [84]:
df['Designation'] = ['Doctor', 'Designer', 'Actor', 'Engineer']
df

    Name  Age      City  Salary Designation
0   John   20  New York   65000      Doctor
1   Anna   34     Paris   70000    Designer
2  Peter   29    Berlin   62000       Actor
3  Linda   42    London   85000    Engineer

#### Removing columns

In [85]:
df.drop('Designation', axis=1, inplace=True)

In [86]:
print(df)

    Name  Age      City  Salary
0   John   20  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [87]:
df.drop(['City', 'Salary'], axis=1)

    Name  Age
0   John   20
1   Anna   34
2  Peter   29
3  Linda   42

In [89]:
print(df)

    Name  Age      City  Salary
0   John   20  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [90]:
df.drop(0, axis=0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [92]:
df

    Name  Age      City  Salary
0   John   20  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### Selecting Rows

In [93]:
df.loc[0]

Name          John
Age             20
City      New York
Salary       65000
Name: 0, dtype: object

In [96]:
df.loc[[0, 2]]

    Name  Age      City  Salary
0   John   20  New York   65000
2  Peter   29    Berlin   62000

In [98]:
df.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

#### Selecting subsets of rows and columns

In [99]:
df

    Name  Age      City  Salary
0   John   20  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [102]:
df.loc[[0, 1]][['City', 'Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [106]:
df.loc[[2, 3]][['Name', 'Age']]

    Name  Age
2  Peter   29
3  Linda   42

#### Conditional Selection

In [107]:
df

    Name  Age      City  Salary
0   John   20  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [111]:
# I only want to see those people whose age is above 30

df[df['Age'] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [114]:
df[(df['Age'] > 30) & (df['City'] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

### 3. Missing Data

#### Finding Missing Data

In [127]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [128]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [129]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [130]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

#### Removing missing data

In [131]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [132]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [133]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [134]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

#### Filling the missing data

In [135]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [136]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [137]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [140]:
values = {'A':0, 'B':100, 'C':300, 'D':400}
df.fillna(value=values) # fills column wise only drop happens row wise

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [141]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [142]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

### 4. Merging, Joining, Concatenation

#### Merging 2 dataframes

In [145]:
# DataFrame 1: Employee info
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary Information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [146]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [147]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [152]:
pd.merge(employees, salaries, on='employee_id', how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [154]:
pd.merge(employees, salaries, on='employee_id', how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [156]:
pd.merge(employees, salaries, on='employee_id', how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [158]:
pd.merge(employees, salaries, on='employee_id', how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

#### Concatenation of 2 dataframes

In [159]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [160]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [161]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [162]:
pd.concat([df1, df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [163]:
pd.concat([df1, df2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

#### Joining 2 data frames

In [164]:
# first dataframe
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie'],
}, index=[1, 2, 3])

# second dataframe
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [165]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [166]:
df2

   score
2     85
3     90
4     75

In [167]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [168]:
df1.join(df2, how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [169]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

In [171]:
df2.join(df1, how='outer')

   score     name
1    NaN    Alice
2   85.0      Bob
3   90.0  Charlie
4   75.0      NaN

### 5. GroupBy and Aggregation

#### GroupBy

In [172]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2025-01-01', periods=8)
}

df = pd.DataFrame(data=data)

In [173]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2025-01-01
1        B    S1    200        15 2025-01-02
2        A    S2    150        12 2025-01-03
3        B    S2    250        18 2025-01-04
4        A    S1    120         8 2025-01-05
5        B    S2    180        20 2025-01-06
6        A    S2    200        15 2025-01-07
7        B    S1    300        25 2025-01-08

In [176]:
# Group by category and calculate the sum of sales

cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [177]:
# Group by store and calculte the sum of sales
cat = df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [179]:
# Group by multiple columns
# Group by category and store

cat = df.groupby(['Category', 'Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

#### Aggregation

In [181]:
print(df['Sales'].mean())

187.5

In [182]:
print(df['Sales'].mode())

0    200
Name: Sales, dtype: int64

In [184]:
print(df['Sales'].median())

190.0

In [187]:
df['Sales'].agg(['mean', 'median', 'min', 'max', 'sum', 'count', 'std'])

mean       187.500000
median     190.000000
min        100.000000
max        300.000000
sum       1500.000000
count        8.000000
std         66.062741
Name: Sales, dtype: float64

### 6. PivotTables

#### Pivot Tables

In [188]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 
               'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 
               'North', 'South'],             
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data=data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

In [189]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    631     78   John  January      Q1
1  2023-01-02       B   West    690     91   Mary  January      Q1
2  2023-01-03       C  North    909     42    Bob  January      Q1
3  2023-01-04       D  South    617     90  Alice  January      Q1
4  2023-01-05       A   East    727     49   John  January      Q1
5  2023-01-06       B   West    596     55   Mary  January      Q1
6  2023-01-07       C  North    440     86    Bob  January      Q1
7  2023-01-08       D  South    792     87  Alice  January      Q1
8  2023-01-09       A   East    528     30   John  January      Q1
9  2023-01-10       B   West    204     48   Mary  January      Q1
10 2023-01-11       C  North    412     90    Bob  January      Q1
11 2023-01-12       D  South    926     68  Alice  January      Q1
12 2023-01-13       A   East    984     91   John  January      Q1
13 2023-01-14       B   West    901     39   Mary  January      Q1
14 2023-01-15       C  North    265     92    Bob  January      Q1
15 2023-01-16       D  South    876     41  Alice  January      Q1
16 2023-01-17       A   East    195     53   John  January      Q1
17 2023-01-18       B   West    372     78   Mary  January      Q1
18 2023-01-19       C  North    190     50    Bob  January      Q1
19 2023-01-20       D  South    420     20  Alice  January      Q1

In [191]:
pd.pivot_table(df, values='Sales', index='Region', columns='Product')

Product      A      B      C      D
Region
East     613.0    NaN    NaN    NaN
North      NaN    NaN  443.2    NaN
South      NaN    NaN    NaN  726.2
West       NaN  552.6    NaN    NaN

In [192]:
pd.pivot_table(df, values='Sales', index='Region', columns='Product', aggfunc='median')

Product      A      B      C      D
Region
East     631.0    NaN    NaN    NaN
North      NaN    NaN  412.0    NaN
South      NaN    NaN    NaN  792.0
West       NaN  596.0    NaN    NaN

In [193]:
pd.pivot_table(df, values='Sales', index='Region', columns='Product', aggfunc='max')

Product      A      B      C      D
Region
East     984.0    NaN    NaN    NaN
North      NaN    NaN  909.0    NaN
South      NaN    NaN    NaN  926.0
West       NaN  901.0    NaN    NaN

In [194]:
pd.pivot_table(df, values='Sales', index='Region', columns='Product', aggfunc='mean')

Product      A      B      C      D
Region
East     613.0    NaN    NaN    NaN
North      NaN    NaN  443.2    NaN
South      NaN    NaN    NaN  726.2
West       NaN  552.6    NaN    NaN

In [196]:
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     613.0    NaN    NaN    NaN  60.2   NaN   NaN   NaN
North      NaN    NaN  443.2    NaN   NaN   NaN  72.0   NaN
South      NaN    NaN    NaN  726.2   NaN   NaN   NaN  61.2
West       NaN  552.6    NaN    NaN   NaN  62.2   NaN   NaN

#### Cross Tabs

In [197]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    631     78   John  January      Q1
1  2023-01-02       B   West    690     91   Mary  January      Q1
2  2023-01-03       C  North    909     42    Bob  January      Q1
3  2023-01-04       D  South    617     90  Alice  January      Q1
4  2023-01-05       A   East    727     49   John  January      Q1
5  2023-01-06       B   West    596     55   Mary  January      Q1
6  2023-01-07       C  North    440     86    Bob  January      Q1
7  2023-01-08       D  South    792     87  Alice  January      Q1
8  2023-01-09       A   East    528     30   John  January      Q1
9  2023-01-10       B   West    204     48   Mary  January      Q1
10 2023-01-11       C  North    412     90    Bob  January      Q1
11 2023-01-12       D  South    926     68  Alice  January      Q1
12 2023-01-13       A   East    984     91   John  January      Q1
13 2023-01-14       B   West    901     39   Mary  January      Q1
14 2023-01-15       C  North    265     92    Bob  January      Q1
15 2023-01-16       D  South    876     41  Alice  January      Q1
16 2023-01-17       A   East    195     53   John  January      Q1
17 2023-01-18       B   West    372     78   Mary  January      Q1
18 2023-01-19       C  North    190     50    Bob  January      Q1
19 2023-01-20       D  South    420     20  Alice  January      Q1

In [200]:
pd.crosstab(df['Region'], df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

### 7. Operations

#### Dataframes basic operations

In [218]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [219]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [220]:
df1.shape

(5, 3)

In [221]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [222]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [223]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [224]:
df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

#### DataFrames Applying Functions

In [225]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [226]:
def square(x):
    return x ** 2

In [227]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [228]:
df1['D'] = df1['B'].apply(square)

In [229]:
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500

In [230]:
df1['E'] = df1['B'].apply(lambda x : x**2)

In [231]:
df1

   A   B    C     D     E
0  1  10  100   100   100
1  2  20  200   400   400
2  3  30  300   900   900
3  4  40  400  1600  1600
4  5  50  500  2500  2500